[camera]
position = [ 0.0, 40.0, 0.0 ]

[chunks]
max_limit = 32
render_distance = 40

[files]
resources_path = 'C:\Users\xflajs00\CLionProjects\minecraft_thingy\resources'

[imgui]
path_icons = 'C:\Users\xflajs00\CLionProjects\minecraft_thingy\resources\icons'

[imgui.cam_window_layout]
collapsed = false

[imgui.clip_checkbox]
checked = false

[imgui.combobox_vox_type]
selected = 'Ice'

[imgui.frustum_culling_checkbox]
checked = false

[imgui.light_pos_slider]
value = [ 0.652999997138977, -1.0, 0.0 ]

[imgui.wireframe_checkbox]
checked = false

[window]
height = 1200
title = 'Minecraft thingy'
width = 1800