[window]
width = 1800
height = 1200
title = "OpenGL"

[files]
resources_path = 'C:\Users\xflajs00\CLionProjects\minecraft_thingy\resources'

[imgui]
path_icons = 'C:\Users\xflajs00\CLionProjects\minecraft_thingy\resources\icons'